# Generated by Django 4.1.1 on 2023-02-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("queryContent", models.TextField()),
                (
                    "contactStatus",
                    models.IntegerField(
                        default=0, verbose_name=[{0: "unsolved", 1: "solved"}]
                    ),
                ),
            ],
        ),
    ]
